# CMake generated Testfile for 
# Source directory: /home/pa01/Mehul/DFTFE/tests/dft/allElectron/real
# Build directory: /home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(real/methane_01.mpirun=4.release "/usr/bin/cmake" "-DTRGT=real.methane_01.mpirun4.release.test" "-DTEST=real/methane_01.mpirun=4.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/real" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/scripts/run_test.cmake")
set_tests_properties(real/methane_01.mpirun=4.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "real" PROCESSORS "4" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real/methane_01.release/mpirun=4" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;0;")
add_test(real/methane_01.mpirun=8.release "/usr/bin/cmake" "-DTRGT=real.methane_01.mpirun8.release.test" "-DTEST=real/methane_01.mpirun=8.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/real" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/scripts/run_test.cmake")
set_tests_properties(real/methane_01.mpirun=8.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "real" PROCESSORS "8" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real/methane_01.release/mpirun=8" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;0;")
add_test(real/methane_01_b.mpirun=8.release "/usr/bin/cmake" "-DTRGT=real.methane_01_b.mpirun8.release.test" "-DTEST=real/methane_01_b.mpirun=8.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/real" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/scripts/run_test.cmake")
set_tests_properties(real/methane_01_b.mpirun=8.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "real" PROCESSORS "8" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real/methane_01_b.release/mpirun=8" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;0;")
add_test(real/oxgen_2neg.mpirun=16.release "/usr/bin/cmake" "-DTRGT=real.oxgen_2neg.mpirun16.release.test" "-DTEST=real/oxgen_2neg.mpirun=16.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/real" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/scripts/run_test.cmake")
set_tests_properties(real/oxgen_2neg.mpirun=16.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "real" PROCESSORS "16" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real/oxgen_2neg.release/mpirun=16" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;0;")
add_test(real/oxygenMolecule_01.mpirun=4.release "/usr/bin/cmake" "-DTRGT=real.oxygenMolecule_01.mpirun4.release.test" "-DTEST=real/oxygenMolecule_01.mpirun=4.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/real" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/scripts/run_test.cmake")
set_tests_properties(real/oxygenMolecule_01.mpirun=4.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "real" PROCESSORS "4" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/real/tests/dft/allElectron/real/oxygenMolecule_01.release/mpirun=4" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installReal/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/real/CMakeLists.txt;0;")
