[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ase-dftfe-socket"
version = "0.1.0.a"
description = "Socket-based ASE interface for DFT-FE"
readme = "README.md"
authors = [
  { name = "Mehul Darak", email = "10pipioff@gmail.com" }
]
license = { text = "LGPL-2.1-or-later" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v2.1 or later (LGPLv2.1+)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "ase>=3.22.0",
    "numpy",
]

[project.urls]
"Homepage" = "https://github.com/dftfeDevelopers/dftfe"

[project.entry-points."ase.calculators"]
dftfe = "dftfe:DFTFE"

[tool.setuptools]
py-modules = ["dftfe"]
