#!/usr/bin/env python3
# ---------------------------------------------------------------------
# Copyright (c) 2017-2025 The Regents of the University of Michigan and DFT-FE
# authors. Part of the DFT-FE code, released under LGPL v2.1 or later.
# ---------------------------------------------------------------------
#
# @author Mehul Darak
#
"""Write the Aurora native decks for the BCC-Mo 431-atom scaling study.

The published Summit deck (DFT-FE v1.0) cannot be run unchanged on a current
build. Five of its keys were renamed or removed, and deal.II parses .prm files
with ``skip_undefined=true`` -- so a stale key costs nothing at parse time and
silently changes the algorithm at run time. The worst of them is ``USE GPU``:
v1.0 read it inside ``subsection GPU``, current DFT-FE declares it at top level
(``utils/runParameters.cc``). Left where it was, the GPU binary runs Chebyshev
filtering on the CPU and the job never finishes.

This script emits decks with the current spellings, one per node count. Physics
is identical to the Summit deck; only the parallel-decomposition knob and the
node count change.

    python3 make_decks.py [outdir]
"""

from __future__ import annotations

import os
import sys

# Aurora: 6 GPUs x 2 tiles = 12 MPI ranks per node.
RANKS_PER_NODE = 12
NODE_COUNTS = (16, 32, 64, 128)

# Mesh is 4913 FE cells (from the Summit run log). Ranks with zero locally-owned
# cells divide by zero in the cell-batch / ELPA grid setup and die on SIGFPE, so
# cells-per-rank is the quantity that bounds this study -- see the handoff doc.
FE_CELLS = 4913

# 0 = DFT-FE's documented thumb rule for the ScaLAPACK/ELPA process grid. The
# Summit deck hard-codes 50 (192 ranks) and 30 (384 ranks); those were tuned for
# Summit's rank counts and topology, and the grid is capped by the rank count
# anyway. Auto is the defensible choice per Aurora rank count. Both arms use the
# same value, so parity is unaffected either way.
SCALAPACK_PROCS = 0

TEMPLATE = """\
# BCC Mo 6x6x6 supercell, 1 vacancy -- 431 atoms, GGA-PBE, Gamma point.
# Aurora native deck for {nodes} nodes x {rpn} ranks/node = {ranks} MPI ranks.
#
# Physics is verbatim from the Summit DFT-FE v1.0 benchmark
#   dftfe-benchmarks/.../BCCMoSuperCells/6x6x6Vac/parameterFileGPU32NodesMPS.prm
# with the v1.0 key spellings migrated to current DFT-FE:
#   USE GPU                            -> top level (was inside subsection GPU)
#   USE MIXED PREC CHEBY               -> USE SINGLE PREC CHEBY
#   USE MIXED PREC CGS O               -> USE MIXED PREC XTOX
#   USE MIXED PREC XTHX SPECTRUM SPLIT -> USE MIXED PREC XTHX
#   SPECTRUM SPLIT CORE EIGENSTATES    -> removed from DFT-FE, dropped
#
# GENERATED by make_decks.py -- edit that, not this.

set SOLVER MODE = GS
set VERBOSITY = 4
set USE GPU = true

subsection GPU
  set AUTO GPU BLOCK SIZES = false
  set FINE GRAINED GPU TIMINGS = true
  set USE GPUDIRECT MPI ALL REDUCE = false
  set USE ELPA GPU KERNEL = true
end

subsection Boundary conditions
  set PERIODIC1 = true
  set PERIODIC2 = true
  set PERIODIC3 = true
  set SELF POTENTIAL RADIUS = 4.0
end

subsection DFT functional parameters
  set EXCHANGE CORRELATION TYPE = GGA-PBE
  set PSEUDOPOTENTIAL CALCULATION = true
  set PSEUDOPOTENTIAL FILE NAMES LIST = pseudo.inp
end

subsection Finite element mesh parameters
  set POLYNOMIAL ORDER = 7
  set POLYNOMIAL ORDER ELECTROSTATICS = 7
  subsection Auto mesh generation parameters
    set MESH SIZE AROUND ATOM = 2.1
    set ATOM BALL RADIUS = 10.0
  end
end

subsection Geometry
  set NATOMS = 431
  set NATOM TYPES = 1
  set ATOMIC COORDINATES FILE = coordinates.inp
  set DOMAIN VECTORS FILE = domainVectors.inp
  subsection Optimization
    set ION FORCE = true
  end
end

subsection Helmholtz problem parameters
  set ABSOLUTE TOLERANCE HELMHOLTZ = 1e-8
  set MAXIMUM ITERATIONS HELMHOLTZ = 10000
end

subsection Poisson problem parameters
  set MAXIMUM ITERATIONS = 10000
  set TOLERANCE = 1e-8
end

subsection SCF parameters
  set MIXING PARAMETER = 0.5
  set COMPUTE ENERGY EACH ITER = false
  set MIXING METHOD = ANDERSON_WITH_KERKER
  set KERKER MIXING PARAMETER = 0.05
  set MIXING HISTORY = 10
  set MAXIMUM ITERATIONS = 100
  set TEMPERATURE = 500
  set TOLERANCE = 1e-4
  subsection Eigen-solver parameters
    set NUMBER OF KOHN-SHAM WAVEFUNCTIONS = 3600
    set CHEBYSHEV POLYNOMIAL DEGREE = 35
    set CHEBYSHEV POLYNOMIAL DEGREE SCALING FACTOR FIRST SCF = 1.5
    set CHEBYSHEV FILTER TOLERANCE = 1e-2
    set CHEBY WFC BLOCK SIZE = 600
    set WFC BLOCK SIZE = 600
    set SUBSPACE ROT DOFS BLOCK SIZE = 20000
    set USE SINGLE PREC CHEBY = true
    set REUSE LANCZOS UPPER BOUND = true
    set ALLOW MULTIPLE PASSES POST FIRST SCF = false
    set USE MIXED PREC XTOX = true
    set USE MIXED PREC CGS SR = true
    set USE MIXED PREC XTHX = true
    set SCALAPACKPROCS = {scalapack}
  end
end
"""


def main():
    # Flat layout on purpose: DFT-FE resolves ATOMIC COORDINATES FILE and
    # DOMAIN VECTORS FILE relative to the working directory, so a deck only runs
    # from a directory that also holds coordinates.inp / domainVectors.inp /
    # pseudo.inp. Keeping them together means the same directory works for the
    # native driver and for read_dftfe().
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(outdir, exist_ok=True)
    for nodes in NODE_COUNTS:
        ranks = nodes * RANKS_PER_NODE
        path = os.path.join(outdir, f"parameterFileAurora{nodes}Nodes.prm")
        with open(path, "w") as fh:
            fh.write(TEMPLATE.format(nodes=nodes, rpn=RANKS_PER_NODE,
                                     ranks=ranks, scalapack=SCALAPACK_PROCS))
        print(f"{path}  ({ranks} ranks, {FE_CELLS / ranks:.1f} FE cells/rank)")


if __name__ == "__main__":
    main()
