# CMake generated Testfile for 
# Source directory: /home/pa01/Mehul/DFTFE/tests/dft/allElectron/complex
# Build directory: /home/pa01/Mehul/DFTFE/build_gpu/release/complex/tests/dft/allElectron/complex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(complex/silicon_01.mpirun=16.release "/usr/bin/cmake" "-DTRGT=complex.silicon_01.mpirun16.release.test" "-DTEST=complex/silicon_01.mpirun=16.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/complex" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/scripts/run_test.cmake")
set_tests_properties(complex/silicon_01.mpirun=16.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "complex" PROCESSORS "16" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/complex/tests/dft/allElectron/complex/silicon_01.release/mpirun=16" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/complex/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/complex/CMakeLists.txt;0;")
add_test(complex/silicon_01_b.mpirun=16.release "/usr/bin/cmake" "-DTRGT=complex.silicon_01_b.mpirun16.release.test" "-DTEST=complex/silicon_01_b.mpirun=16.release" "-DEXPECT=PASSED" "-DBINARY_DIR=/home/pa01/Mehul/DFTFE/build_gpu/release/complex" "-P" "/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/scripts/run_test.cmake")
set_tests_properties(complex/silicon_01_b.mpirun=16.release PROPERTIES  FIXTURES_REQUIRED "test_dependency/dftfe_exe.executable" LABEL "complex" PROCESSORS "16" TIMEOUT "5000" WORKING_DIRECTORY "/home/pa01/Mehul/DFTFE/build_gpu/release/complex/tests/dft/allElectron/complex/silicon_01_b.release/mpirun=16" _BACKTRACE_TRIPLES "/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/macros/macro_deal_ii_add_test.cmake;619;add_test;/storage/dftfeDependenciesNoMKL/dealii/installComplex/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;383;deal_ii_add_test;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/complex/CMakeLists.txt;3;DEAL_II_PICKUP_TESTS;/home/pa01/Mehul/DFTFE/tests/dft/allElectron/complex/CMakeLists.txt;0;")
