#!/usr/bin/env python3
# ---------------------------------------------------------------------
# Copyright (c) 2017-2025 The Regents of the University of Michigan and DFT-FE
# authors. Part of the DFT-FE code, released under LGPL v2.1 or later.
# ---------------------------------------------------------------------
#
# @author Mehul Darak
#
"""
ASE-DFTFE Automated Test Suite
================================
Runs a configurable set of test cases, compares results against
references.json, and reports PASS/FAIL.

Usage:
    python test_suite.py \\
        --dftfe-real    /path/to/build_gpu/release/real/dftfe \\
        --dftfe-complex /path/to/build_gpu/release/complex/dftfe \\
        --psp-library   /path/to/psp_library \\
        --np 8 \\
        [--no-device] \\
        [--tests co2_nonperiodic n2_nonperiodic ...]

Missing references
------------------
A reference of ``null`` (or an absent key) is a **FAILURE**, not a licence to
invent one. It means nothing is pinned for that quantity, so the test cannot
regress and reporting PASS would be a lie.

Seeding a reference is therefore an explicit, deliberate act::

    python test_suite.py ... --seed

and should only ever be done on a binary you trust, from a run you have
looked at. Without ``--seed`` this script never writes references.json.
"""

import argparse
import importlib.util
import json
import os
import sys
import traceback
from datetime import datetime

import numpy as np
from ase.units import Bohr, Hartree, eV, Angstrom

# ── Constants ──────────────────────────────────────────────────────────────
ENERGY_TOL_HA = 1e-10   # |E - E_ref| < this (Hartree, 10 decimal places)
FORCE_TOL_HA_BOHR = 1e-8  # max |F_computed - F_ref| per component (Ha/Bohr, 8 decimal places)

# Map test name → which binary kind to use
BINARY_KIND = {
    "co2_nonperiodic":  "real",
    "n2_nonperiodic":   "real",
    "relax_o2":         "real",
    "al_slab_semiperiodic": "real",   # gamma-only: periodic in x/y, open along z
    "graphene_periodic": "complex",
    "al_bulk_periodic":  "complex",
}

# Nothing is run-only any more. relax_o2 used to be, on the theory that a
# relaxed energy is too path-dependent to pin at 1e-10 Ha -- but that is only
# true across configurations, and the provenance gate now rules those out.
# Within one configuration BFGS is deterministic, so leaving it unpinned was
# giving up the only multi-step coverage the suite has.
RUN_ONLY = set()

ALL_TESTS = list(BINARY_KIND.keys())

CASES_DIR = os.path.join(os.path.dirname(__file__), "cases")
REFS_FILE  = os.path.join(os.path.dirname(__file__), "references.json")

_NO_REF_HINT = ("re-run with --seed on a trusted binary to pin it deliberately")


# ── Helpers ────────────────────────────────────────────────────────────────

def load_case(name: str):
    """Dynamically import cases/<name>.py and return its `run` function."""
    path = os.path.join(CASES_DIR, f"{name}.py")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Case file not found: {path}")
    spec = importlib.util.spec_from_file_location(name, path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.run


def provenance(args, kind: str) -> dict:
    """What must be identical for the 1e-10 Ha tolerance to be meaningful.

    1e-10 Ha is a determinism bar, not a physics bar, and DFT-FE is only that
    reproducible against *itself in the same configuration*. Measured on this
    project (PROJECT.md 5.7): a 4x rank change moves the energy by 6.4e-9 Ha and
    forces by ~5 digits -- 60x and 1000x outside the tolerances here, with
    nothing wrong. Those are MPI reduction-order differences, not regressions.

    So a reference is only comparable to a run that shares its binary, its rank
    count and its device. Recording that with the number is what lets the suite
    tell "the code changed" apart from "you ran it differently", instead of
    reporting the second as the first.
    """
    binary = {"real": args.dftfe_real, "complex": args.dftfe_complex}[kind]
    try:
        st = os.stat(binary)
        stamp = f"{st.st_size}:{int(st.st_mtime)}"
    except OSError:
        stamp = "unknown"
    return {
        "binary": os.path.abspath(binary),
        "binary_stamp": stamp,
        "np": args.np,
        "use_device": bool(args.use_device),
    }


# What must match for a 1e-10 Ha comparison to mean anything. The binary is
# deliberately NOT here. References generated by make_references.py come from
# native pGD, a different executable from the one the ASE arm drives -- that is
# the whole point, since a reference produced by the interface can only detect
# change, never wrongness. What cannot differ is the numerical environment:
# a 4x rank change alone moves the energy 6.4e-9 Ha (PROJECT.md 5.7).
#
# The unavoidable assumption is that pGD and the branch are built equivalently
# (same flags, same deal.II, physics sources identical). Verified by hand on
# 2026-08-13; it is not machine-checkable from here, so it is stated rather than
# silently relied upon.
CONFIG_KEYS = ("np", "use_device")


def provenance_mismatch(ref: dict, now: dict):
    """Config fields that differ between the reference's run and this one."""
    old = ref.get("provenance")
    if not old:
        return None  # pre-provenance reference; treated as unverifiable
    return [k for k in CONFIG_KEYS if old.get(k) != now.get(k)] or []


def check_energy(computed: float, ref: float) -> tuple:
    """Returns (passed: bool, diff_ha: float). Tolerance: 1e-10 Ha."""
    diff = abs(computed - ref)
    return diff < ENERGY_TOL_HA, diff


def check_forces(computed: np.ndarray, ref: np.ndarray) -> tuple:
    """
    Pointwise per-component comparison.
    Returns (passed: bool, max_abs_diff_ha_bohr: float, worst_atom: int, worst_comp: int).
    Tolerance: 1e-8 Ha/Bohr per component.
    """
    diff = np.abs(computed - ref)          # shape (N, 3)
    max_diff = diff.max()
    idx = np.unravel_index(diff.argmax(), diff.shape)
    return max_diff < FORCE_TOL_HA_BOHR, max_diff, int(idx[0]), int(idx[1])


# ── Main ───────────────────────────────────────────────────────────────────

def run_suite(args):
    tests = args.tests or ALL_TESTS
    bins  = {"real": args.dftfe_real, "complex": args.dftfe_complex}

    # Validate binary paths
    for kind, path in bins.items():
        if not path or not os.path.isfile(path):
            print(f"[ERROR] {kind} binary not found: {path}", flush=True)
            sys.exit(1)

    # Load references
    with open(REFS_FILE) as f:
        refs = json.load(f)

    results    = {}
    any_seeded = False
    timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_lines  = [f"ASE-DFTFE Test Suite  —  {timestamp}", "=" * 60]
    if args.seed:
        log_lines.append("--seed given: null references WILL be overwritten "
                         "with this run's values.")

    for line in log_lines:
        print(line, flush=True)

    for name in tests:
        if name not in BINARY_KIND:
            print(f"[SKIP] Unknown test: {name}", flush=True)
            continue

        print(f"\nRunning: {name} ...", flush=True)
        kind    = BINARY_KIND[name]
        dftfe_b = bins[kind]
        ref     = refs.get(name, {})

        try:
            run_fn = load_case(name)
            energy_ha, forces_ha_per_bohr, stress = run_fn(
                dftfe_bin=dftfe_b,
                psp_library=args.psp_library,
                np_tasks=args.np,
                use_device=args.use_device,
            )
        except Exception:
            tb = traceback.format_exc()
            msg = f"[FAIL] {name}  →  EXCEPTION\n{tb}"
            print(msg, flush=True)
            results[name] = {"status": "FAIL", "reason": "exception", "traceback": tb}
            log_lines.append(msg)
            continue

        # ── provenance gate ──
        # Checked before the numbers, because comparing across configurations
        # produces a FAIL that says "regression" when it means "different rank
        # count". At 1e-10 Ha that is not a corner case, it is the common case.
        now_prov = provenance(args, kind)
        drift = provenance_mismatch(ref, now_prov)
        if args.seed:
            refs.setdefault(name, {})["provenance"] = now_prov
        elif drift:
            old = ref["provenance"]
            detail = "; ".join(f"{k}: ref {old.get(k)!r} vs now {now_prov.get(k)!r}"
                               for k in drift)
            line = (f"[MISMATCH] {name}\n  reference was produced under a different "
                    f"numerical configuration -- {detail}\n  Not compared: a 4x rank "
                    f"change alone moves the energy 6.4e-9 Ha, 60x this tolerance, "
                    f"with nothing wrong. Re-generate for this configuration, or run "
                    f"at the recorded one.")
            print(line, flush=True)
            log_lines.append(line)
            results[name] = {"status": "MISMATCH", "drift": drift}
            continue
        elif drift is None and ref.get("energy_ha") is not None:
            log_lines.append(f"  note: {name} reference predates provenance "
                             f"tracking; its configuration is unverifiable.")
        elif (ref.get("provenance") or {}).get("generator") == "native-pgd":
            # Worth stating in the log: a PASS here is the interface agreeing
            # with an independent implementation, not with its own past output.
            print(f"  reference: native pGD "
                  f"({os.path.basename(ref['provenance'].get('binary',''))}), "
                  f"np={ref['provenance'].get('np')}", flush=True)

        # ── RUN_ONLY: just check it didn't crash ──
        if name in RUN_ONLY:
            line = f"[{'PASS':6s}] {name}  (run-only: completed successfully)"
            print(line, flush=True)
            log_lines.append(line)
            results[name] = {"status": "PASS", "energy_note": "run-only", "force_note": ""}
            continue

        # ── Energy check ──
        ref_energy = ref.get("energy_ha")
        seeded = False

        if ref_energy is None:
            if args.seed:
                refs.setdefault(name, {})["energy_ha"] = energy_ha
                seeded = any_seeded = True
                energy_status = "SEEDED"
                energy_note   = f"energy = {energy_ha:.10e} Ha  (saved as reference)"
            else:
                energy_status = "FAIL"
                energy_note   = (
                    f"energy = {energy_ha:.10e} Ha  |  ref = null  "
                    f"|  NO ENERGY REFERENCE — nothing is pinned; {_NO_REF_HINT}"
                )
        else:
            e_pass, e_diff = check_energy(energy_ha, ref_energy)
            energy_status  = "PASS" if e_pass else "FAIL"
            energy_note    = (
                f"energy = {energy_ha:.10e} Ha  |  ref = {ref_energy:.10e} Ha  "
                f"|  diff = {e_diff:.3e} Ha"
            )

        # ── Force check ──
        force_status = None
        force_note   = ""
        if forces_ha_per_bohr is not None:
            ref_forces_list = ref.get("forces_ha_per_bohr")
            if ref_forces_list is None or seeded:
                if args.seed:
                    refs.setdefault(name, {})["forces_ha_per_bohr"] = \
                        forces_ha_per_bohr.tolist()
                    any_seeded   = True
                    force_status = "SEEDED"
                    force_note   = f"forces saved as reference ({forces_ha_per_bohr.shape[0]} atoms)"
                else:
                    force_status = "FAIL"
                    force_note   = (
                        f"NO FORCE REFERENCE — 'forces_ha_per_bohr' is null or "
                        f"absent; {_NO_REF_HINT}"
                    )
            else:
                ref_forces = np.array(ref_forces_list)
                f_pass, max_diff, worst_atom, worst_comp = check_forces(forces_ha_per_bohr, ref_forces)
                comp_labels = ['x', 'y', 'z']
                force_status = "PASS" if f_pass else "FAIL"
                force_note   = (
                    f"max |F_computed - F_ref| = {max_diff:.3e} Ha/Bohr  "
                    f"(tol 1e-8, worst: atom {worst_atom} {comp_labels[worst_comp]})"
                )

        # ── Overall status ──
        # FAIL wins over SEEDED: a pinned energy that regressed is still a
        # regression even if this run happened to seed the forces beside it.
        if energy_status == "FAIL" or force_status == "FAIL":
            overall = "FAIL"
        elif seeded or force_status == "SEEDED":
            overall = "SEEDED"
        else:
            overall = "PASS"

        results[name] = {
            "status":       overall,
            "energy_ha":    energy_ha,
            "energy_note":  energy_note,
            "force_note":   force_note,
        }

        line = f"[{overall:6s}] {name}\n  {energy_note}"
        if force_note:
            line += f"\n  {force_note}"
        print(line, flush=True)
        log_lines.append(line)

    # ── Save updated references, but ONLY if seeding was asked for and used ──
    if any_seeded:
        with open(REFS_FILE, "w") as f:
            json.dump(refs, f, indent=2)
        print(f"\nReferences updated: {REFS_FILE}", flush=True)

    # ── Summary ──
    summary = "\n" + "=" * 60 + "\nSUMMARY\n" + "=" * 60
    counts  = {"PASS": 0, "FAIL": 0, "SEEDED": 0, "FAIL(exc)": 0}
    for name, r in results.items():
        s = r["status"]
        counts[s] = counts.get(s, 0) + 1
        summary  += f"\n  [{s:6s}] {name}"
    summary += f"\n{'-'*60}"
    summary += f"\nPASS={counts.get('PASS',0)}  FAIL={counts.get('FAIL',0)}  SEEDED={counts.get('SEEDED',0)}"
    print(summary, flush=True)
    log_lines.append(summary)

    # ── Write results file ──
    results_file = f"test_results_{timestamp}.txt"
    with open(results_file, "w") as f:
        f.write("\n".join(log_lines))
    print(f"\nResults written to: {results_file}", flush=True)

    # Exit 1 if any FAIL
    if counts.get("FAIL", 0) > 0:
        sys.exit(1)


# ── CLI ────────────────────────────────────────────────────────────────────

def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="ASE-DFTFE Automated Test Suite"
    )
    parser.add_argument(
        "--dftfe-real",
        required=True,
        help="Path to real DFT-FE binary (for gamma-only tests)",
    )
    parser.add_argument(
        "--dftfe-complex",
        required=True,
        help="Path to complex DFT-FE binary (for k-point tests)",
    )
    parser.add_argument(
        "--psp-library",
        required=True,
        help="Path to directory containing *.upf pseudopotential files",
    )
    parser.add_argument(
        "--np",
        type=int,
        default=8,
        help="Number of MPI tasks (default: 8)",
    )
    parser.add_argument(
        "--no-device",
        dest="use_device",
        action="store_false",
        default=True,
        help="Run on the host (USE GPU off). Required when --dftfe-real / "
             "--dftfe-complex point at CPU-only builds: those have no DEVICE "
             "branch, so use_device=True leaves DFT-FE with no solver at all.",
    )
    parser.add_argument(
        "--seed",
        action="store_true",
        help="Write this run's values into references.json wherever the "
             "reference is null. Without it, a null reference is a FAILURE "
             "and references.json is never modified.",
    )
    parser.add_argument(
        "--tests",
        nargs="+",
        metavar="TEST",
        help=f"Subset of tests to run. Available: {ALL_TESTS}",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    run_suite(parse_args())
